# Generated by Django 3.0.8 on 2020-07-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippetcomment_snippetlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetcomment',
            old_name='liked_at',
            new_name='created_at',
        ),
    ]
