# Generated by Django 3.0.8 on 2020-07-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20200729_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('snippet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippet.Snippet')),
            ],
        ),
    ]
